#!/usr/bin/env bash

#rows=3
cols=2

ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
    -*)
        usage
        exit 1
        ;;
    *)
        ARGS+=("$1")
        shift
        ;;
    esac
done

usage() {
    echo "usage: jpggrid"
    echo "Rename sequentially named .jpg files into x y positions"
}

row=0
col=0
for fn in $(ls *.jpg |sort); do
    dst=$(printf "r%02d_c%02d.jpg" $row $col)
    echo mv $fn $dst
    col=$(($col + 1))
    if [ $col = $cols ] ; then
        row=$(($row + 1))
        col=0
    fi
done


