'''
This file is part of pr0ntools
Copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
Licensed under a 2 clause BSD license, see COPYING for details
'''

import time

def get_js_file_header(name, version):
	ret = ''
	ret += '//Generated by pr0ntools on %s\n' % time.strftime("%d/%m/%Y %H:%M:%S") 
	ret += '//%s version %s\n' % (name, version)
	ret += '\n'
	return ret

